### ISSUE TITLE
Crash on very large input with headers and footers

### ISSUE THREAD

**Issue by zhm** [wkhtmltopdf/wkhtmltopdf#1681]
I'm using wkhtmltopdf to generate PDF reports from database records. There seems to be a bug when attempting to generate a PDF from a very large input when combined with headers and footers. I'm able to reproduce it and I'm attaching a full test case that's reproducible on Linux and Mac as of c22928d.

When I try it with a smaller input html file, it does work. But when I increase the input size, it crashes every time. Bear in mind that I know this is a ridiculously large input and possibly unreasonable to fix, but I wanted to submit my findings in case there's a legitimate bug here :)

Here is the crash output:

```
QPaintDevice: Cannot destroy paint device that is being painted

Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: 13 at address: 0x0000000000000000
0x0000000101361b5b in QList<wkhtmltopdf::settings::PdfObject>::detach_helper_grow ()
```

Here is the gdb trace:

```
(gdb) bt
#0  0x0000000101361b5b in QList<wkhtmltopdf::settings::PdfObject>::detach_helper_grow ()
#1  0x0000000101363a7c in QList<wkhtmltopdf::settings::PdfObject>::detach_helper_grow ()
#2  0x000000010002cb96 in wkhtmltopdf::settings::HeaderFooter::~HeaderFooter ()
#3  0x000000010001a317 in wkhtmltopdf::settings::LoadPage::LoadPage ()
#4  0x0000000101a4457d in QList<wkhtmltopdf::settings::PdfObject>::detach_helper_grow ()
#5  0x0000000100047aed in QList<wkhtmltopdf::settings::PdfObject>::detach_helper_grow ()
#6  0x0000000101a4457d in QList<wkhtmltopdf::settings::PdfObject>::detach_helper_grow ()
#7  0x0000000101a49632 in QList<wkhtmltopdf::settings::PdfObject>::detach_helper_grow ()
#8  0x0000000101a40233 in QList<wkhtmltopdf::settings::PdfObject>::detach_helper_grow ()
#9  0x0000000101205e7c in QList<wkhtmltopdf::settings::PdfObject>::detach_helper_grow ()
#10 0x0000000101207226 in QList<wkhtmltopdf::settings::PdfObject>::detach_helper_grow ()
#11 0x0000000101a2e3e6 in QList<wkhtmltopdf::settings::PdfObject>::detach_helper_grow ()
#12 0x0000000101a5b620 in QList<wkhtmltopdf::settings::PdfObject>::detach_helper_grow ()
#13 0x0000000101a5bdda in QList<wkhtmltopdf::settings::PdfObject>::detach_helper_grow ()
#14 0x0000000101a2e7b1 in QList<wkhtmltopdf::settings::PdfObject>::detach_helper_grow ()
#15 0x000000010001a66f in wkhtmltopdf::settings::LoadPage::LoadPage ()
#16 0x00000001000392fc in wkhtmltopdf::settings::PdfGlobal::~PdfGlobal ()
#17 0x00000001000045d4 in ?? ()
```

Here are the input files with cause the crash: http://cl.ly/0F2T3Q0V1c43

Here are the same input files as a gist: https://gist.github.com/zhm/c0c5e39b1f95cce28b2e

The command I'm running which causes the crash:

``` sh
wkhtmltopdf --page-size Letter --margin-top 0.75in --margin-bottom 0.75in --margin-left 0.75in --margin-right 0.75in --encoding UTF-8 --header-html header.html --footer-html footer.html test.html test.pdf
```

It processes some of the headers and footers, and then starts outputting this error many times:

```
Error: Failed loading page file:///Users/zacmcc/Documents/wkhtmltopdf_bug/footer.html?page=4686&section=9995&sitepage=4686&title=Report&subsection=&frompage=1&subsubsection=&topage=4688&doctitle=Report&sitepages=4688&webpage=test.html&time=12:44 PM&date=5/1/14 (sometimes it will work just to ignore this error with --load-error-handling ignore)
Error: Failed loading page file:///Users/zacmcc/Documents/wkhtmltopdf_bug/header.html?page=4687&section=9997&sitepage=4687&title=Report&subsection=&frompage=1&subsubsection=&topage=4688&doctitle=Report&sitepages=4688&webpage=test.html&time=12:44 PM&date=5/1/14 (sometimes it will work just to ignore this error with --load-error-handling ignore)
Error: Failed loading page file:///Users/zacmcc/Documents/wkhtmltopdf_bug/footer.html?page=4687&section=9997&sitepage=4687&title=Report&subsection=&frompage=1&subsubsection=&topage=4688&doctitle=Report&sitepages=4688&webpage=test.html&time=12:44 PM&date=5/1/14 (sometimes it will work just to ignore this error with --load-error-handling ignore)
Error: Failed loading page file:///Users/zacmcc/Documents/wkhtmltopdf_bug/header.html?page=4688&section=9999&sitepage=4688&title=Report&subsection=&frompage=1&subsubsection=&topage=4688&doctitle=Report&sitepages=4688&webpage=test.html&time=12:44 PM&date=5/1/14 (sometimes it will work just to ignore this error with --load-error-handling ignore)
Error: Failed loading page file:///Users/zacmcc/Documents/wkhtmltopdf_bug/footer.html?page=4688&section=9999&sitepage=4688&title=Report&subsection=&frompage=1&subsubsection=&topage=4688&doctitle=Report&sitepages=4688&webpage=test.html&time=12:44 PM&date=5/1/14 (sometimes it will work just to ignore this error with --load-error-handling ignore)
```

**Comment by Gioggiolo** [comment]
Hello, i'm having the same issue:
[log.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/81758/log.txt)
In my case, it happens when the number of pages are about 500+

I modified limits.conf(and rebooted) unsuccesfully:
```
* soft nofile 100000
* hard nofile 100000
root soft nofile 100000
root hard nofile 100000
```

**Comment by lorenzos** [comment]
@Gioggiolo Take a look at my workaround here: https://github.com/wkhtmltopdf/wkhtmltopdf/issues/2093#issuecomment-167955213

**Comment by Gioggiolo** [comment]
@lorenzos 
Thank you, do you mean "after changing header and footer to local paths"?
All my files passed as parameters are already local files "/tmp/tmp_wkhtmlto_pdf_XXXXXX.html", take a look at my attacked log.
However HTML images are local files but linked ad external urls because of virtualhosts.
My test case:
```
wkhtmltopdf --no-outline --margin-right '0' --margin-left '0' --load-error-handling 'ignore' '/tmp/tmp_wkhtmlto_pdf_D9IQqS.html' --header-html '/tmp/tmp_wkhtmlto_pdf_Br3B7p.html' --footer-html '/tmp/tmp_wkhtmlto_pdf_M0jbh9.html' '/tmp/tmp_wkhtmlto_pdf_IatFp4.html' --header-html '/tmp/tmp_wkhtmlto_pdf_Q3g0KB.html' --footer-html '/tmp/tmp_wkhtmlto_pdf_7hXh5k.html' '/tmp/tmp_wkhtmlto_pdf_LerKtg.html' --header-html '/tmp/tmp_wkhtmlto_pdf_DjvALN.html' --footer-html '/tmp/tmp_wkhtmlto_pdf_e8FC7w.html' '/tmp/tmp_wkhtmlto_pdf_c3ZZys.html' --header-html '/tmp/tmp_wkhtmlto_pdf_CDQ3PZ.html' --footer-html '/tmp/tmp_wkhtmlto_pdf_1pEtcJ.html' '/tmp/tmp_wkhtmlto_pdf_vDQoGE.html' --header-html '/tmp/tmp_wkhtmlto_pdf_hha2Vb.html' --footer-html '/tmp/tmp_wkhtmlto_pdf_wcJajV.html' '/tmp/tmp_wkhtmlto_pdf_M06n8Q.html' --header-html '/tmp/tmp_wkhtmlto_pdf_WqYgao.html' --footer-html '/tmp/tmp_wkhtmlto_pdf_H0AhE7.html' '/tmp/tmp_wkhtmlto_pdf_N5ftk5.html' --header-html '/tmp/tmp_wkhtmlto_pdf_5jUQbB.html' --footer-html '/tmp/tmp_wkhtmlto_pdf_YlX6fl.html' '/tmp/tmp_wkhtmlto_pdf_GJscqP.pdf'
```
It works if I split it in two processes.
Process 1, about 300 generated pages:
```
wkhtmltopdf --no-outline --margin-right '0' --margin-left '0' --load-error-handling 'ignore' '/tmp/tmp_wkhtmlto_pdf_D9IQqS.html' --header-html '/tmp/tmp_wkhtmlto_pdf_Br3B7p.html' --footer-html '/tmp/tmp_wkhtmlto_pdf_M0jbh9.html' '/tmp/tmp_wkhtmlto_pdf_IatFp4.html' --header-html '/tmp/tmp_wkhtmlto_pdf_Q3g0KB.html' --footer-html '/tmp/tmp_wkhtmlto_pdf_7hXh5k.html' '/tmp/tmp_wkhtmlto_pdf_LerKtg.html' --header-html '/tmp/tmp_wkhtmlto_pdf_DjvALN.html' --footer-html '/tmp/tmp_wkhtmlto_pdf_e8FC7w.html' '/tmp/tmp_wkhtmlto_pdf_c3ZZys.html' --header-html '/tmp/tmp_wkhtmlto_pdf_CDQ3PZ.html' --footer-html '/tmp/tmp_wkhtmlto_pdf_1pEtcJ.html' '/tmp/tmp_wkhtmlto_pdf_vDQoGE.html' --header-html '/tmp/tmp_wkhtmlto_pdf_hha2Vb.html' --footer-html '/tmp/tmp_wkhtmlto_pdf_wcJajV.html' '/tmp/tmp_wkhtmlto_pdf_M06n8Q.html' --header-html '/tmp/tmp_wkhtmlto_pdf_WqYgao.html' --footer-html '/tmp/tmp_wkhtmlto_pdf_H0AhE7.html' '/tmp/tmp_wkhtmlto_pdf_GJscqP_1.pdf'
```
Process 2, about 200 generated pages:
```
wkhtmltopdf --no-outline --margin-right '0' --margin-left '0' --load-error-handling 'ignore' '/tmp/tmp_wkhtmlto_pdf_N5ftk5.html' --header-html '/tmp/tmp_wkhtmlto_pdf_5jUQbB.html' --footer-html '/tmp/tmp_wkhtmlto_pdf_YlX6fl.html' '/tmp/tmp_wkhtmlto_pdf_GJscqP_2.pdf'
```

**Comment by lorenzos** [comment]
@Gioggiolo Yes, I was referring to that. I'm sorry to hear it hasn't worked for you. Can you do something to avoid external URLs (i.e pre-download the content and locally reference it)? From what I understood, the problem is with opened sockets, not opened files, and also links to a local webserver count as an opened socket. Or at least try to temporarily remove the external links to see if that's the real cause of the problem.

**Comment by Gioggiolo** [comment]
I removed all external links from my files (headers and footers were already clean), but the issue persists.
I also tried to use empty headers and footers, unsuccessfully.
It just works if i don't use headers and footers.

**Comment by eLBati** [comment]
Hi @ashkulz , did you document the issue? I can't find it.
Thanks!

**Comment by fmdl** [comment]
Dear, When you try to generate a big pdf (over 200 pages) with header and footer, you are an error -11. It is a limitation of max handle file per process. (default is 256 for mac). But the wkhtmltopdf open for each page the header and the footer. to change this value : http://stackoverflow.com/questions/16526783/python-subprocess-too-many-open-files

In terminal do : ulimit -n 10000
Check : ulimit -a

**Comment by rennanhm** [comment]
I modified limits.conf unsuccesfully, i try ulimit -n 10000 but doesnt work too
