### ISSUE TITLE
Can not build on Ubuntu Trusty

### ISSUE THREAD

**Issue by jkrasnoo** [wkhtmltopdf/wkhtmltopdf#1707]
I'm having trouble building wkhtmltopdf on Ubuntu Trusty. I need both wkhtmltopdf and wkhtmltoimage for pimcore. I'm getting errors when running the build script. Perhaps I'm missing something?

jamie@ubuntu-server:~/src/wkhtmltopdf$ sudo scripts/build.py setup-schroot-trusty
Traceback (most recent call last):
  File "scripts/build.py", line 795, in <module>
    main()
  File "scripts/build.py", line 792, in main
    globals()['build_%s' % BUILDERS[config]](final_config, os.path.realpath%28basedir%29)
  File "scripts/build.py", line 413, in build_setup_schroot
    install_packages('git', 'debootstrap', 'schroot', 'rinse')
  File "scripts/build.py", line 392, in install_packages
    lines = get_output('dpkg-query', '--list', *names).split('\n')
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by JD-Robbs** [comment]
I have the same issue while following this guide: https://github.com/wkhtmltopdf/wkhtmltopdf/blob/master/INSTALL.md

I'm cloning from master and get the aforementioned error when trying to build for Ubuntu 14.0.4 32bit.

**Comment by zp12132016** [comment]
I have the same issue, is anyone solved this?
Traceback (most recent call last):
  File "scripts/build.py", line 1128, in <module>
    main()
  File "scripts/build.py", line 1124, in main
    globals()['check_%s' % BUILDERS[config]](final_config)
  File "scripts/build.py", line 881, in check_linux_generic
    chroot_shell(chroot_env, 'gcc --version')
  File "scripts/build.py", line 426, in chroot_shell
    distro  = get_chroot_list().get(name)
  File "scripts/build.py", line 600, in get_chroot_list
    for line in get_output('schroot', '--list').split('\n'):
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by wissem** [comment]
I'm trying to build current master, but I have the same issue on Debian Stretch . Anyone found a workaround for this?
