### ISSUE TITLE
debug build fails for wkhmltoimage (precise)

### ISSUE THREAD

**Issue by Mrten** [wkhtmltopdf/wkhtmltopdf#1805]
It compiles wkhtmltopdf fine, but it seems to miss a ruby dependency for wkhtmltoimage:

```
install -m 755 -p "../../bin/wkhtmltoimage" "/var/home/builder/wkhtmltopdf/static-build/precise-amd64-dbg/dist/bin/wkhtmltoimage"
make[1]: Leaving directory `/var/home/builder/wkhtmltopdf/static-build/precise-amd64-dbg/app/src/image'
/usr/lib/ruby/vendor_ruby/1.8/rubygems/dependency.rb:247:in `to_specs': Could not find fpm (>= 0) amongst [] (Gem::LoadError)
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/dependency.rb:256:in `to_spec'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems.rb:1208:in `gem'
    from /usr/local/bin/fpm:18
schroot -c wkhtmltopdf-precise-amd64 -- ./build.sh
command failed: exit code 256
```

I just git pulled (hour or two ago), pretty recent version.

**Comment by mshannaq** [comment]
I search for 
shell('gem install -V fpm -N')
and replace with 
shell('gem install fpm ronn --no-ri --no-rdoc')
