### ISSUE TITLE
issue when building from source

### ISSUE THREAD

**Issue by clarkk** [wkhtmltopdf/wkhtmltopdf#2690]
```
# git clone git://github.com/wkhtmltopdf/wkhtmltopdf.git && cd wkhtmltopdf
# scripts/build.py jessie-amd64
Traceback (most recent call last):
  File "scripts/build.py", line 1256, in <module>
    main()
  File "scripts/build.py", line 1252, in main
    globals()['check_%s' % BUILDERS[config]](final_config)
  File "scripts/build.py", line 989, in check_linux_schroot
    chroot_shell(rchop(config, '-dbg'), 'gcc --version')
  File "scripts/build.py", line 505, in chroot_shell
    distro  = get_chroot_list().get(name)
  File "scripts/build.py", line 699, in get_chroot_list
    for line in get_output('schroot', '--list').split('\n'):
AttributeError: 'NoneType' object has no attribute 'split'
```

Debian jessie

Have also tried

```
# cmake . && make && make install
CMake Error: The source directory "/var/bin/wkhtmltopdf" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

**Comment by dankank** [comment]
Am 27.11.2015 um 15:35 schrieb clarkk:

**Comment by neo13tomas** [comment]
same here

**Comment by mhmoudgmal** [comment]
any updates on this issue?

**Comment by mzalazar** [comment]
same thing here, Ubuntu 16.04

**Comment by ashkulz** [comment]
Please read INSTALL.md, it contains detailed instructions.
