### ISSUE TITLE
Running wkthmltopdf in virtualenv giving error

### ISSUE THREAD

**Issue by priyavartkyava** [wkhtmltopdf/wkhtmltopdf#3008]
Hi,

The same code is running fine without virtualenv.

Even when I activate virtualenv and run wkthltopdf on console it works but with browser it is throwing error.

Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/test/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "/home/ubuntu/.virtualenvs/test/local/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/hooks/framework_django.py", line 499, in wrapper
    return wrapped(_args, *_kwargs)
  File "/home/ubuntu/.virtualenvs/test/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, _args, *_kwargs)
  File "/app/test/outbound/views.py", line 1557, in packing_slip
    pdf_file_data = pdfkit.from_string(html_string, False)
  File "/home/ubuntu/.virtualenvs/test/local/lib/python2.7/site-packages/pdfkit/api.py", line 68, in from_string
    return r.to_pdf(output_path)
  File "/home/ubuntu/.virtualenvs/test/local/lib/python2.7/site-packages/pdfkit/pdfkit.py", line 113, in to_pdf
    'https://github.com/JazzCore/python-pdfkit/wiki/Using-wkhtmltopdf-without-X-server' % stderr.decode('utf-8'))
IOError: wkhtmltopdf: cannot connect to X server

**Comment by priyavartkyava** [comment]
just to add that I am running uwsgi server and nginx as proxy.

**Comment by Tomsgu** [comment]
Closing as this should not be an issue in 0.12.5. Please re-open it if the problem still persists.
