### ISSUE TITLE
Intermittent segfault mid-conversion (C-bindings)

### ISSUE THREAD

**Issue by anowell** [wkhtmltopdf/wkhtmltopdf#3045]
I've been working on a [Rust wrapping](https://github.com/anowell/wkhtmltox-sys), but keep tripping over segfaults in the C-bindings. I put together minimal [C example](https://github.com/anowell/wkhtmltox-sys/blob/master/examples/convert-string.c) and [equivalent Rust example](https://github.com/anowell/wkhtmltox-sys/blob/master/examples/convert-string.rs) that simply convert a short string `<b>foo</b>bar` and both segfault ~50% of the time. (I've also tried variations of 'page' and 'out' settings, and still encounter segfaults regularly).

```
$ gcc -g -Wall examples/convert-string.c -o target/convert-string-c -lwkhtmltox
$ target/convert-string-c                                                      
Version: 0.12.3
Phase: Loading page
  0
 10
 50
100
[1]    3617 segmentation fault (core dumped)  target/convert-string-c
$ target/convert-string-c
Version: 0.12.3
Phase: Loading page
  0
 10
 50
100
Phase: Printing pages
 -1
Phase: Done
Finished: 1
Calling wkhtmltopdf_get_output
Received 5123 bytes.
```

```
Thread 1 "convert-string-" received signal SIGSEGV, Segmentation fault.
0x00007ffff3bc54ca in QString::fromLocal8Bit(char const*, int) () from /usr/lib/libQtCore.so.4
(gdb) bt
#0  0x00007ffff3bc54ca in QString::fromLocal8Bit(char const*, int) () from /usr/lib/libQtCore.so.4
#1  0x00007ffff3c8c2c1 in QCoreApplication::arguments() () from /usr/lib/libQtCore.so.4
#2  0x00007ffff45cea0f in ?? () from /usr/lib/libQtGui.so.4
#3  0x00007ffff45cf834 in ?? () from /usr/lib/libQtGui.so.4
#4  0x00007fffefa06c38 in _SmcProcessMessage () from /usr/lib/libSM.so.6
#5  0x00007fffef7f646c in IceProcessMessages () from /usr/lib/libICE.so.6
#6  0x00007ffff3c9e590 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) () from /usr/lib/libQtCore.so.4
#7  0x00007ffff3cef83e in QSocketNotifier::activated(int) () from /usr/lib/libQtCore.so.4
#8  0x00007ffff3ca8d4b in QSocketNotifier::event(QEvent*) () from /usr/lib/libQtCore.so.4
#9  0x00007ffff454c2dc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#10 0x00007ffff4553136 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQtGui.so.4
#11 0x00007ffff3c8a4dd in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQtCore.so.4
#12 0x00007ffff3cbae52 in ?? () from /usr/lib/libQtCore.so.4
#13 0x00007ffff18c6dd7 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#14 0x00007ffff18c7040 in ?? () from /usr/lib/libglib-2.0.so.0
#15 0x00007ffff18c70ec in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#16 0x00007ffff3cba83e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#17 0x00007ffff45f5336 in ?? () from /usr/lib/libQtGui.so.4
#18 0x00007ffff3c8dc91 in QCoreApplication::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQtCore.so.4
#19 0x00007ffff7b9874f in ?? () from /usr/lib/libwkhtmltox.so.0
#20 0x00007ffff7bbe4fd in wkhtmltopdf_convert () from /usr/lib/libwkhtmltox.so.0
#21 0x0000000000400ee0 in main () at examples/convert-string.c:54
```

(Arch Linux)

**Comment by anowell** [comment]
After a bit more digging, I suspect the Arch Linux [wkhtmltopdf package](https://www.archlinux.org/packages/community/x86_64/wkhtmltopdf/) may be dynamically depending on a version of qtwebkit (currently 2.3.4) that doesn't actually play nice with wkhtmltopdf? Uninstalling that and downloading the latest release from wkhtmltopdf.org (which I assume statically includes qtwebkit) seems to avoid this segfault, but unfortunately that results in broken SSL (per #3001).

**Comment by anowell** [comment]
Gonna close this as my original issue is solved by just not using the Arch distributed package which uses qtwebkit dynamically. I'm not sure if the Arch packaging issue belongs here. I'd be happy to open an issue specifically for that if there is a need for tracking that here.
