### ISSUE TITLE
Installation behind a proxy failed

### ISSUE THREAD

**Issue by reisenmachtfreude** [wkhtmltopdf/wkhtmltopdf#3229]
A proxy for apt is configured and working but executing build.py results in the following error.
I'm using Ubuntu 16.04.1 LTS
```
sudo scripts/build.py setup-schroot-generic
******************* generic-amd64
Failed to fetch : http://mirror.centos.org/centos/6/os/x86_64/Packages/
	500 Can't connect to mirror.centos.org:80

Traceback (most recent call last):
  File "scripts/build.py", line 1121, in <module>
    main()
  File "scripts/build.py", line 1118, in main
    globals()['build_%s' % BUILDERS[config]](final_config, basedir)
  File "scripts/build.py", line 655, in build_setup_schroot
    open(os.path.join(root_dir, 'etc/yum.conf'), 'a').write('exclude = *.i?86\n')
IOError: [Errno 2] No such file or directory: '/var/chroot/wkhtmltox-generic-amd64/etc/yum.conf'
```

**Comment by ashkulz** [comment]
Probably need to set the http_proxy environment variable beforehand?
