### ISSUE TITLE
Odoo server Error

### ISSUE THREAD

**Issue by ArpithaRaoS** [wkhtmltopdf/wkhtmltopdf#3427]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/addons/report/controllers/main.py", line 96, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/report/models/report.py", line 265, in get_pdf
    context.get('set_viewport_size'),
  File "/usr/lib/python2.7/dist-packages/odoo/addons/report/models/report.py", line 443, in _run_wkhtmltopdf
    wkhtmltopdf = [_get_wkhtmltopdf_bin()] + command_args + local_command_args
  File "/usr/lib/python2.7/dist-packages/odoo/addons/report/models/report.py", line 46, in _get_wkhtmltopdf_bin
    return find_in_path('wkhtmltopdf')
  File "/usr/lib/python2.7/dist-packages/odoo/tools/misc.py", line 65, in find_in_path
    return which(name, path=os.pathsep.join(path))
  File "/usr/lib/python2.7/dist-packages/odoo/tools/which.py", line 148, in which
    raise IOError(ENOENT, '%s not found' % (mode & X_OK and 'command' or 'file'), file)
IOError: [Errno 2] command not found: 'wkhtmltopdf'

**Comment by rubiagatra** [comment]
how do you install wkhtml?

**Comment by sathwiksunderreddy** [comment]
you have to set wkhtml bin folder path in environmental variables to get it accessed 

Hope it helps you out

**Comment by Tomsgu** [comment]
Closing as this issue is not connected with wkhtmltopdf itself.
