### ISSUE TITLE
wkhtmltopdf command works in bash but fails mostly silently in Unicorn/Nginx/Rails

### ISSUE THREAD

**Issue by chrisandrewca** [wkhtmltopdf/wkhtmltopdf#3562]
Heyo - I'm having a bit o trouble generating PDFs from my rails app. You can see the command
 `/home/fm-cafe/xwkhtmltopdf --page-size Letter --enable-local-file-access /home/fm-cafe/app/current/public/invoice_generated.html /home/fm-cafe/app/current/public/invoice.pdf`
is failing when run from rails / unicorn / nginx.

The command works when I run it from bash and generates the PDF!
I've checked out the Unicorn and Production logs but no avail. Exitstatus = 141 and seems to be in to_pdf... have not been able to find further details as of yet. Please help!

Specific error is:
Error performing OrdersPaidJob (Job ID: 16acf7b1-b075-4f5d-9cd0-869259a19cb2) from Async(default) in 345.8ms: RuntimeError (command failed (exitstatus=141): /home/fm-cafe/xwkhtmltopdf --page-size Letter --enable-local-file-access /home/fm-cafe/app/current/public/invoice_generated.html /home/fm-cafe/app/current/public/invoice.pdf):

Rails production log
```
[2017-07-12T11:37:37.312658 #4082] ERROR -- : [ActiveJob] [OrdersPaidJob] [16acf7b1-b075-4f5d-9cd0-869259a19cb2] Error performing OrdersPaidJob (Job ID: 16acf7b1-b075-4f5d-9cd0-869259a19cb2) from Async(default) in 345.8ms: RuntimeError (command failed (exitstatus=141): /home/fm-cafe/xwkhtmltopdf --page-size Letter --enable-local-file-access /home/fm-cafe/app/current/public/invoice_generated.html /home/fm-cafe/app/current/public/invoice.pdf):
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/pdfkit-0.8.2/lib/pdfkit/pdfkit.rb:71:in `to_pdf'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/pdfkit-0.8.2/lib/pdfkit/pdfkit.rb:76:in `to_file'
/home/fm-cafe/app/releases/26/app/jobs/orders_paid_job.rb:68:in `perform'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/execution.rb:37:in `block in perform_now'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/i18n-0.8.6/lib/i18n.rb:257:in `with_locale'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:117:in `instance_exec'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/logging.rb:24:in `block (4 levels) in <module:Logging>'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications.rb:166:in `block in instrument'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/notifications.rb:166:in `instrument'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/logging.rb:23:in `block (3 levels) in <module:Logging>'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/logging.rb:44:in `block in tag_logger'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/tagged_logging.rb:69:in `tagged'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/logging.rb:44:in `tag_logger'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/logging.rb:20:in `block (2 levels) in <module:Logging>'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:117:in `instance_exec'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:135:in `run_callbacks'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/execution.rb:33:in `perform_now'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/execution.rb:22:in `block in execute'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:108:in `block in run_callbacks'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/railtie.rb:26:in `block (4 levels) in <class:Railtie>'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/execution_wrapper.rb:85:in `wrap'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/reloader.rb:68:in `block in wrap'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/execution_wrapper.rb:85:in `wrap'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/reloader.rb:67:in `wrap'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/railtie.rb:25:in `block (3 levels) in <class:Railtie>'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:117:in `instance_exec'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.2/lib/active_support/callbacks.rb:135:in `run_callbacks'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/execution.rb:20:in `execute'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/activejob-5.1.2/lib/active_job/queue_adapters/async_adapter.rb:68:in `perform'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/home/fm-cafe/app/releases/26/vendor/bundle/ruby/2.4.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

Contents of xwkhtmltopdf
```
#!/bin/bash
XVFB="/usr/bin/xvfb-run"
WKHTMLTOPDF="/usr/bin/wkhtmltopdf"

$XVFB -a -s "-screen 0 1280x1024x16" $WKHTMLTOPDF $@
```

Server details
```
lsb_release -a && uname -a && ruby -v
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
Linux farmhousecafe-sf01 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
gem 'rails', '~> 5.1.2'
wkhtmltopdf 0.12.2.4 via apt-get install wkhtmltopdf
```

Unicorn config
```
app_path = File.expand_path(File.join(File.dirname(__FILE__), '../../'))

#listen '127.0.0.1:4000'
listen File.join(app_path, 'shared/unicorn.sock'), :backlog => 64

worker_processes 4

working_directory File.join(app_path, 'current')
pid File.join(app_path, 'shared/unicorn.pid')
stderr_path File.join(app_path, 'current/log/unicorn.log')
stdout_path File.join(app_path, 'current/log/unicorn.log')
```

**Comment by daudmalik06** [comment]
@chrisandrewca there are always some problems with wkhtmltopdf for this purpose born new library which uses chrome headless as a back-end try this 
https://github.com/daudmalik06/PhpChromeToPdf

or you can directly use google chrome headless if want to.

**Comment by chrisandrewca** [comment]
@daudmalik06 thank you! I will check this out.
