### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by clarkk** [wkhtmltopdf/wkhtmltopdf#3719]
Debian 8

```
cd /var/bin
git clone --recursive https://github.com/wkhtmltopdf/wkhtmltopdf.git
cd wkhtmltopdf
scripts/build.py linux-generic-amd64
```

error
```
Traceback (most recent call last):
  File "scripts/build.py", line 1128, in <module>
    main()
  File "scripts/build.py", line 1124, in main
    globals()['check_%s' % BUILDERS[config]](final_config)
  File "scripts/build.py", line 881, in check_linux_generic
    chroot_shell(chroot_env, 'gcc --version')
  File "scripts/build.py", line 426, in chroot_shell
    distro  = get_chroot_list().get(name)
  File "scripts/build.py", line 600, in get_chroot_list
    for line in get_output('schroot', '--list').split('\n'):
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by ashkulz** [comment]
See [wkhtmltopdf/packaging](https://github.com/wkhtmltopdf/packaging) for updated approach for building packages.
