### ISSUE TITLE
[Errno 12] Cannot allocate memory

### ISSUE THREAD

**Issue by cogdev99** [wkhtmltopdf/wkhtmltopdf#3776]
hi,

I'm getting this error randomly on our production server which is hosted on AWS t2.micro.

**OS Info**
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
Linux 4.4.0-64-generic x86_64

Wkhtmltopdf version: 0.12.4

Traceback (most recent call last):
  File "./panel/views.py", line 1544, in generate_pdf
    pdf = wkhtmltopdf(pages=[temp_file.name], **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/wkhtmltopdf/utils.py", line 110, in wkhtmltopdf
    return check_output(ck_args, **ck_kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1235, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

If I restart nginx and uwsgi for django, it will fix it, but comes back randomly at a later stage. 

Not sure where to start looking as it's hard to replicate. Does anyone have encountered similar issue or have any pointer on what could be wrong? 

Thanks!

**Comment by ashkulz** [comment]
So move to a higher instance, some pages can take a lot of RAM to process.
