### ISSUE TITLE
Will not work with ol.Graticule if showLabels is true

### ISSUE THREAD

**Issue by dnorgaard-usgs** [wkhtmltopdf/wkhtmltopdf#4167]
I have a page that wkhtmltopdf will convert with following JavaScript:

  // add graticule
  var graticule = new ol.Graticule({
      // the style to use for the lines, optional.
      lonLabelPosition: 1,
      lonLabelStyle: new ol.style.Text({
        font: '12px Calibri,sans-serif',
        textBaseline: 'top',
        fill: new ol.style.Fill({
           color: 'rgba(0,0,0,1)'
        }),
        stroke: new ol.style.Stroke({
           color: 'rgba(255,255,255,1)',
           width: 3
        })
      }),
//      showLabels: true,
      strokeStyle: new ol.style.Stroke({
        color: 'rgba(128,128,128,0.5)',
        width: 1,
        lineDash: [4, 4]
      }),
  });
  graticule.setMap(map)

However, in order to show lat/lon labels, I need to uncomment the showLabels: true line.  When I do the pdf does not generate and I get the following error:

[Thu Nov 01 21:59:15.249838 2018] [php7:error] [pid 10169] [client 130.118.152.250:56053] PHP Fatal error:  Uncaught Symfony\\Component\\Process\\Exception\\ProcessSignaledException: The process has been signaled with signal "11". in /var/www/html/vendor/symfony/process/Process.php:393\nStack trace:\n#0 /var/www/html/vendor/symfony/process/Process.php(202): Symfony\\Component\\Process\\Process->wait()\n#1 /var/www/html/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php(526): Symfony\\Component\\Process\\Process->run()\n#2 /var/www/html/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php(176): Knp\\Snappy\\AbstractGenerator->executeCommand('/var/www/html/v...')\n#3 /var/www/html/vendor/knplabs/knp-snappy/src/Knp/Snappy/Pdf.php(63): Knp\\Snappy\\AbstractGenerator->generate('http://localhos...', '/tmp/knp_snappy...', Array, false)\n#4 /var/www/html/vendor/knplabs/knp-snappy/src/Knp/Snappy/AbstractGenerator.php(222): Knp\\Snappy\\Pdf->generate('http://localhos...', '/tmp/knp_snappy...', Array)\n#5 /var/www/html/ivans/preview_pdf.php(27): Knp\\Snappy\\AbstractGenerator->getOutput('http://localhos...')\n#6 {main}\n  thrown in /var/www/html/vendor/symfony/process/Process.php on line 393, referer: 

and is syslog:

Nov  1 22:00:53 localhost kernel: wkhtmltopdf-amd[13076]: segfault at 0 ip 000000000144adf3 sp 00007ffd83b3add0 error 4 in wkhtmltopdf-amd64[400000+23d0000

By setting showLabels = true, all it does is render the lat/lon labels:

![image](https://user-images.githubusercontent.com/25251719/47884380-bb0d5180-dded-11e8-9388-9fe097dce5a6.png)

Without (I can generate pdf with this map):

![image](https://user-images.githubusercontent.com/25251719/47884418-dd9f6a80-dded-11e8-9489-6390326c855b.png)

I tried tinkering with the lat/lon formatters to see if it was the degrees, minute, or seconds symbol that was causing it, but it does not seem so.  The simplest text still results in same error (can't generate pdf), e.g.:

![image](https://user-images.githubusercontent.com/25251719/47884503-38d15d00-ddee-11e8-800a-9ef52d19fdc1.png)

**Comment by dnorgaard-usgs** [comment]
Btw, version info: wkhtmltopdf 0.12.5 (with patched qt)

**Comment by dnorgaard-usgs** [comment]
For some reason it works if I overwrite the graticule style and comment out the stroke, e.g.:

  var graticule = new ol.Graticule({
      // the style to use for the lines, optional.
      lonLabelPosition: 1,
      lonLabelStyle: new ol.style.Text({
        font: '12px Calibri,sans-serif',
        textBaseline: 'top',
/**
        fill: new ol.style.Fill({
           color: 'rgba(0,0,0,1)'
        }),
        stroke: new ol.style.Stroke({
           color: 'rgba(255,255,255,1)',
           width: 3
        })
*/
      }),
      latLabelStyle: new ol.style.Text({
        font: '12px Calibri,sans-serif',
        textAlign: 'end',
/**
        fill: new Fill({
          color: 'rgba(0,0,0,1)'
        }),
        stroke: Stroke({
          color: 'rgba(255,255,255,1)',
          width: 3
        })
*/
      }),


I commented out the fill too just because I didn't need it.  Not sure why the stroke would cause a problem though.

**Comment by dnorgaard-usgs** [comment]
I previously opened a ticket with openlayers on this btw: https://github.com/openlayers/openlayers/issues/8816.  I assume the problem is with wkhtmltopdf but not sure.
