### ISSUE TITLE
Error converting HTML to PDF

### ISSUE THREAD

**Issue by supriya123d** [wkhtmltopdf/wkhtmltopdf#4415]
Hi, I am trying to convert html to pdf using wkhtmltopdf, below is the HTML code

<span><img src=https://crm.bascrm.com/Documents/ProposalDocuments/ImagesFiles/2-23060-101620190712114024123.jpeg></span><span><img src=https://crm.bascrm.com/Documents/ProposalDocuments/ImagesFiles/2-23060-101620190712114027482.jpeg></span><span><img src=https://crm.bascrm.com/Documents/ProposalDocuments/ImagesFiles/2-23060-101620190712114030623.jpeg></span><span><img src=https://crm.bascrm.com/Documents/ProposalDocuments/ImagesFiles/2-23060-101620190712114033607.jpeg></span><span><img src=https://crm.bascrm.com/Documents/ProposalDocuments/ImagesFiles/2-23060-101620190712114036357.jpeg></span><span><img src=https://crm.bascrm.com/Documents/ProposalDocuments/ImagesFiles/2-23060-101620190712114038732.jpeg></span><span><img src=https://crm.bascrm.com/Documents/ProposalDocuments/ImagesFiles/2-23060-101620190712114040404.jpeg></span><span><img src=https://crm.bascrm.com/Documents/ProposalDocuments/ImagesFiles/2-23060-101620190712114041545.jpeg></span>

Its not converting and giving error , where as if we pass just one <span> tag with one img inside it works perfectly.

Problem generating PDF from HTML, URLs: msg:D:\somepath\2-58196-1016-E_sign(2019-07-12).html, outputFilename: 2-58196-1016-E_sign(2019-07-12) ---> System.Exception
  at SendInvoice.HtmlToPdf(String pdfOutputLocation, String outputFilenamePrefix, String[] urls, String[] options, String pdfHtmlToPdfExePath) in d:\somepath\SendInvoice.cs:line 3734
  --- End of inner exception stack trace ---
  at SendInvoice.HtmlToPdf(String pdfOutputLocation, String outputFilenamePrefix, String[] urls, String[] options, String pdfHtmlToPdfExePath) in d:\somepath\SendInvoice.cs:line 3739
  at createPdf.createFilesByString(EditFunctions data, String path, String id, Boolean footertrue) in d:\somepath\createPdf.cs:line 1439

We are using the attached code (https://github.com/wkhtmltopdf/wkhtmltopdf/files/3386437/htmltopdf.txt)
We are on IIS Server, is there any permission issue for converting big data?

Please help.

Regards
Supriya 
[htmltopdf.txt](https://github.com/wkhtmltopdf/wkhtmltopdf/files/3386437/htmltopdf.txt)

**Comment by PhilterPaper** [comment]
It's not clear to me what the problem is. The pure HTML at the top converts properly to PDF, using wkHTMLtoPDF 0.12.5 (patched qt) on Windows 10 command line, producing an 8 page document. 

As for htmltopdf.txt, it looks like maybe C++ code (I don't have a C/C++ compiler) ... what is it, what do I do with it, and what should I expect for results? Does it invoke wkHTMLtoPDF somewhere, and if so, what version?

**Comment by supriya123d** [comment]
Hi, we are using 0.12.4 version of wkhtmltopdf, and the attached file contain asp.net code in it.

We have a process where we write the images at a location and create a html string and pass it to the exe to convert into pdf using the attached asp.net code.

Will also try the latest version today.

**Comment by PhilterPaper** [comment]
I take it that your starting point is a series of page scans (as .jpeg)? The first thing I'd do is check whether your scanner software can already directly output a multipage PDF just from a series of scans. I think I've seen that before. If it can only do a single page PDF at a time, from one scan, you still could use one of a number of PDF utilities to merge the pages into one PDF. Anyway, something to consider.

The ASP.Net code is to produce the HTML file, and then invoke wkHTMLtoPDF to convert it? You might first just grab the HTML file (if you haven't, already) and see if it converts correctly. Is that what you showed at the top of your post? I'm not sure that omitting `<html>` and `<body>` tags is doing any harm, or that those `<span>` tags are helping at all, but if the bare HTML file converts on your PC, that part of the process is presumably good.

Most hosts don't like heavy duty utilities such as wkHTMLtoPDF running on their server, and would rather you do such work offline. Often, vital libraries and compilers are removed from servers so that you can't run arbitrary programs. I'm not familiar with working with .Net, so I can't tell you if that's what the error message is telling you. If these .jpeg images are being uploaded from a PC-attached scanner, you might find it easier anyway to generate the PDF on the PC, and upload just that.

**Comment by getgnu** [comment]
See, it makes a weird mistake like the one below. What could be the reason?

```
root@Dell:/home/fortran/Masaüstü# wkhtmltopdf http://getgnu.org getgnu.pdf
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Loading page (1/2)
QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
Printing pages (2/2)                                               
Done                                                           
Exit with code 1 due to network error: OperationCanceledError
```

**Comment by ashkulz** [comment]
Doesn't look like you're using the version from the downloads page, but the one packaged with your distribution.

**Comment by getgnu** [comment]
Thank you. I think so. I did the installation from the system repositories.

**Comment by getgnu** [comment]
I picked her up. This time I have installed Ubuntu 18.04 (bionic) at https://wkhtmltopdf.org/downloads.html. As if he gave a mistake again but I got the .pdf and .ps printouts. The error output was something like the following:

`fortran@Dell:~$ wkhtmltopdf http://getgnu.org getgnu.pdf
Loading pages (1/6)
Error: Failed to load https://fonts.googleapis.com/css?family=Ubuntu300,300italic,regular,italic,500,500italic,700,700italic|Droid+Serifregular,italic,700,700italic, with network status code 299 and http status code 400 - Error downloading https://fonts.googleapis.com/css?family=Ubuntu300,300italic,regular,italic,500,500italic,700,700italic%7CDroid+Serifregular,italic,700,700italic - server replied: Bad Request
Warning: Failed to load https://likegeeks.com/wp-content/uploads/2017/05/01-convert-array-to-object-using-php.png (ignore)
Warning: Failed to load https://likegeeks.com/wp-content/uploads/2017/05/02-convert-object-to-array-using-php.png (ignore)
Counting pages (2/6)                                               
Resolving links (4/6)                                                       
Loading headers and footers (5/6)                                           
Printing pages (6/6)
Done                                                                        
Exit with code 1 due to network error: UnknownContentError`

Thank you very much.

**Comment by ashkulz** [comment]
I think that there are some CSS issues, see the error messages (might be a network/firewall issue).

**Comment by Eesha-Jain** [comment]
Here is a great video! This integrates both HTML + CSS + images into a PDF: https://www.youtube.com/watch?v=zmJV6VN2h2E . Hopefully this helps with your error
