### ISSUE TITLE
Error: PDF could not be generated!  Command Error: /home/ubuntu/.rbenv/versions/2.6.0/lib/ruby/2.6.0/pathname.rb:43:in `chop_basename': undefined method `match?' for /\A(?-mix:\/)?\z/:Regexp (NoMethodError)

### ISSUE THREAD

**Issue by Manidavid** [wkhtmltopdf/wkhtmltopdf#4632]
Am using wicked_pdf gem and it works fine in my local development and production envs, but i deployed it to aws ec2 instance and trying to generate the pdf in production it doesn't works.

This is my setup:

**Gemfile**
```
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
```
**versions**

> wicked_pdf-2.0.1
> wkhtmltopdf-binary-0.12.5.4
> 

**config/initializers/wicked_pdf.rb**
```
WickedPdf.config = {
  # Path to the wkhtmltopdf executable: This usually isn't needed if using
  # one of the wkhtmltopdf-binary family of gems.
  # exe_path: '/usr/local/bin/wkhtmltopdf',
  #   or
  # exe_path: Gem.bin_path('wkhtmltopdf-binary', 'wkhtmltopdf')

  # Layout file to be used for all PDFs
  # (but can be overridden in `render :pdf` calls)
  # layout: 'pdf.html',
}
```
**controller/users_controller.rb**
```
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Profile",
        disposition: 'attachment',
        template: "users/show.html.erb"
      end
    end
  end
```
I Already have html view in /views/users/show.html.erb.

**Production error logs**

```
Completed 500 Internal Server Error in 197ms (ActiveRecord: 3.5ms)
F, [2020-03-09T09:44:15.138616 #17187] FATAL -- : [ba8d5272-a497-44c8-badf-872d6421d466]   
F, [2020-03-09T09:44:15.138678 #17187] FATAL -- : [ba8d5272-a497-44c8-badf-872d6421d466] RuntimeError (Failed to execute:
["/data/apps/project-path/vendor/bundle/ruby/2.6.0/bin/wkhtmltopdf", "file:////tmp/wicked_pdf20200309-17187-1cnpjpn.html", "/tmp/wicked_pdf_generated_file20200309-17187-1g27mun.pdf"]
Error: PDF could not be generated!
 Command Error: /home/ubuntu/.rbenv/versions/2.6.0/lib/ruby/2.6.0/pathname.rb:43:in `chop_basename': undefined method `match?' for /\A(?-mix:\/)?\z/:Regexp (NoMethodError)
Did you mean?  match
	from /home/ubuntu/.rbenv/versions/2.6.0/lib/ruby/2.6.0/pathname.rb:359:in `plus'
	from /home/ubuntu/.rbenv/versions/2.6.0/lib/ruby/2.6.0/pathname.rb:351:in `+'
	from /home/ubuntu/.rbenv/versions/2.6.0/lib/ruby/2.6.0/pathname.rb:188:in `parent'
	from /home/ubuntu/.rbenv/versions/2.6.0/lib/ruby/2.6.0/bundler/shared_helpers.rb:29:in `root'
	from /home/ubuntu/.rbenv/versions/2.6.0/lib/ruby/2.6.0/bundler.rb:234:in `root'
	from /home/ubuntu/.rbenv/versions/2.6.0/lib/ruby/2.6.0/bundler.rb:246:in `app_config_path'
	from /home/ubuntu/.rbenv/versions/2.6.0/lib/ruby/2.6.0/bundler.rb:273:in `settings'
	from /home/ubuntu/.rbenv/versions/2.6.0/lib/ruby/2.6.0/bundler.rb:84:in `configured_bundle_path'
	from /home/ubuntu/.rbenv/versions/2.6.0/lib/ruby/2.6.0/bundler.rb:351:in `use_system_gems?'
	from /home/ubuntu/.rbenv/versions/2.6.0/lib/ruby/2.6.0/bundler.rb:541:in `configure_gem_path'
	from /home/ubuntu/.rbenv/versions/2.6.0/lib/ruby/2.6.0/bundler.rb:534:in `configure_gem_home_and_path'
	from /home/ubuntu/.rbenv/versions/2.6.0/lib/ruby/2.6.0/bundler.rb:66:in `configure'
	from /home/ubuntu/.rbenv/versions/2.6.0/lib/ruby/2.6.0/bundler.rb:134:in `definition'
	from /home/ubuntu/.rbenv/versions/2.6.0/lib/ruby/2.6.0/bundler.rb:101:in `setup'
	from /home/ubuntu/.rbenv/versions/2.6.0/lib/ruby/2.6.0/bundler/setup.rb:20:in `<top (required)>'
	from /home/ubuntu/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/ubuntu/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
):
F, [2020-03-09T09:44:15.138720 #17187] FATAL -- : [ba8d5272-a497-44c8-badf-872d6421d466]   
F, [2020-03-09T09:44:15.138753 #17187] FATAL -- : [ba8d5272-a497-44c8-badf-872d6421d466] app/controllers/users_controller.rb:27:in `block (2 levels) in show'
[ba8d5272-a497-44c8-badf-872d6421d466] app/controllers/users_controller.rb:24:in `show'
```

**Comment by ashkulz** [comment]
This looks an error in wicked_pdf or your code, please create an issue in that project if still relevant.
