### ISSUE TITLE
Large html conversion issue

### ISSUE THREAD

**Issue by Igladyshev** [wkhtmltopdf/wkhtmltopdf#5236]
**Description**  
I have started using wkhmltopdf with pdfkit on Docker. My task is to convert large html document (95MB+) to pdf. 
It doesn't work when trying to convert straight away, it would fail with weird error:
```
The switch --header-right, is not support using unpatched qt, and will be ignored.QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-astro'

[2022-07-28 14:42:18,416] {decorators.py:86} ERROR - Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sdp_airflow_dag_base/decorators.py", line 81, in wrapper
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sdp_airflow_csv_to_pdf/__init__.py", line 165, in execute
    total_volumes=files_number)
  File "/usr/local/lib/python3.7/site-packages/sdp_airflow_pdf_support/__init__.py", line 185, in convert
    result = self.to_pdf(html_out, self.css)
  File "/usr/local/lib/python3.7/site-packages/sdp_airflow_pdf_support/__init__.py", line 219, in to_pdf
    return pdfkit.from_string(html_data, options=options, configuration = config, css="report.css")
  File "/usr/local/lib/python3.7/site-packages/pdfkit/api.py", line 75, in from_string
    return r.to_pdf(output_path)
  File "/usr/local/lib/python3.7/site-packages/pdfkit/pdfkit.py", line 201, in to_pdf
    self.handle_error(exit_code, stderr)
  File "/usr/local/lib/python3.7/site-packages/pdfkit/pdfkit.py", line 158, in handle_error
    raise IOError("wkhtmltopdf exited with non-zero code {0}. error:\n{1}".format(exit_code, error_msg))
OSError: wkhtmltopdf exited with non-zero code -9. error:
The switch --header-right, is not support using unpatched qt, and will be ignored.QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-astro'
```
 It was when I installed the latest version available for apt-get (0.12.5)
 so, I split it to smaller parts. Then I installed version 0.12.3.2 and get very similar error, but instead of clear error message, it was just "Unknown error"

Then I started splitting to smaller pieces, so less than a third file size would run over an hour without producing anything, and even smaller than 10MB would be generated in 25 minutes.

Please advice?

Igor

**Comment by archergod** [comment]
I recently have to make large file, but my large file is PDF with 200 MB file size due to lots of images, So from that I can tell one thing, if you have lot of images then you need to increase your Docker/Linux max file capabilities. I don't recall the term yet. Also the slowness can be due to RAM is not enough in Docker, I suggest you try to run natively and see the difference it make, Then customize your docker for it.

**Comment by Sicos1977** [comment]
https://github.com/Sicos1977/ChromeHtmlToPdf
